pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, redirect, url_for, g, flash

from pybo import db
from pybo.forms import AnswerForm
from pybo.models import Question, Answer
from pybo.views.auth_views import login_required

bp = Blueprint('answer', __name__, url_prefix='/answer')

@bp.route('/create/<int:question_id>', methods=['POST']) # methods=('POST') 이렇게 써도 상관 X
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content'] # 폼태그에서 내용 받아온 것

        # 1번 방식
        # answer = Answer(content=content, create_date=datetime.now()) # create 함수
        # question.answer_set.append(answer) # 역으로 append해서 답변 등록

        # 2번 방식
        answer = Answer(question=question, content=content, create_date=datetime.now(), user_id=g.user.id)
        db.session.add(answer)

        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('question/question_detail.html', question=question, form=form) # AnswerForm

@bp.route('/modify/<int:answer_id>', methods=['GET', 'POST']) # 수정페이지로 넘어가야하니까 get post 둘 다 사용
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=answer.question_id))
    if request.method == 'POST':
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', question_id=answer.question_id))
    else: # GET 요청
            form = AnswerForm(obj=answer)
    return render_template('answer/answer_form.html', form=form)

@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('삭제권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question._list'))

pybo/views/question_views.py
import os
from datetime import datetime

from flask import Blueprint, render_template, request, redirect, url_for, g, flash, current_app
from werkzeug.utils import secure_filename

from pybo import db
from pybo.forms import QuestionForm, AnswerForm
from pybo.models import Question, Answer, User
from pybo.views.auth_views import login_required

bp = Blueprint('question', __name__, url_prefix='/question')  # question이 별칭

@bp.route('/list/')  # question으로 간 다음 하위인 list로 감
def _list():  # list는 예약어여서 앞에 _붙여줌
    page = request.args.get('page', default=1, type=int)  # 페이지 / request => url(question/list/) 가져와서 뒤에 페이지 파라미터 추가
    kw = request.args.get('kw', default='', type=str)  # 검색 키워드
    question_list = Question.query.order_by(Question.create_date.desc())
    if kw:
        search = f'%%{kw}%%'
        sub_query = db.session.query(Answer.question_id, Answer.content, User.username) \
            .join(User, Answer.user_id == User.id).subquery()
        question_list = question_list.join(User) \
            .outerjoin(sub_query, sub_query.c.question_id == Question.id) \
            .filter(Question.subject.ilike(search) |  # 질문제목
                    Question.content.ilike(search) |  # 질문내용
                    User.username.ilike(search) |  # 질문작성자
                    sub_query.c.content.ilike(search) |  # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    ) \
            .distinct()
    question_list = question_list.paginate(page=page, per_page=10)  # 한 페이지에 보여야 할 게시글 수
    return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw)

@bp.route('/detail/<int:question_id>/') # <url parameter> -> question 아이디만 받아서 원하는 부분만 보여줌 / 문자열로 고정하면 수정이 어려움
def detail(question_id):
    form = AnswerForm() # 질문 상세 템플릿에 답변 폼 추가
    question = Question.query.get_or_404(question_id)  # get 말고 get_or_404 쓰면 값이 없을 때 404 page를 보여줌 / ctrl누르고 클릭하면 함수 정의 보여줌
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/create/', methods=['GET', 'POST']) # POST 방식 = 사용자에게 입력받은 값을 DB에 넣어줌
@login_required
def create():
    form = QuestionForm() # 사용자가 입력한 내용이 튜플로 들어감
    if request.method =='POST' and form.validate_on_submit():
        # 폼에서 받은 이미지 파일 처리
        image_file = form.image.data
        image_path = None
        if image_file:
            # 저장 경로 설정 : 오늘 날짜 폴더생성
            today = datetime.now().strftime('%Y%m%d')
            upload_folder = os.path.join(current_app.root_path, 'static/photo', today) # current ~ path 까지가 pybo
            os.makedirs(upload_folder, exist_ok=True)
            # 파일 저장
            filename = secure_filename(image_file.filename)
            file_path = os.path.join(upload_folder, filename)
            image_file.save(file_path)

            # DB에는 파일 저장 경로만 넣어줌(static 기준으로 상대경로)
            image_path = f'photo/{today}/{filename}'

        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now(),
                            user_id=g.user.id, image_path=image_path) # Models.py
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form) # 괄호 안에 form은 form 모듈

@bp.route('/modify/<int:question_id>', methods=['GET', 'POST']) # 수정으로 이동할 때 get, 수정한 내용을 저장할 때 post
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id) # 질문 조회
    if g.user != question.user:
        flash('수정권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':  # POST 요청할 때
        form =QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question) # 폼 모듈에서 수정된 내용을 알아서 보내주는 함수 populate_obj
            question.modify_date = datetime.now() # 여기서 업데이트 동작을 해서 session.add는 안해도 됨
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:  # GET 요청할 때
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)

@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=question_id))
    else:
        db.session.delete(question)
        db.session.commit()
    return redirect(url_for('question._list'))

pybo/templates/question/question_detail.html
<!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css">-->
<!--<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"> css가 파일 안에 있으면 filename='/css/style.css -->

{% extends 'base.html' %} <!-- base.html을 상속받는다는 뜻 -->
{% block content %}

<div class="container my-3">
    <!-- flash오류(권한이 없는데(=> 평소엔 볼 일 없는데 가끔 서버처리가 오류나면 수정버튼이 보일 수 있음) 수정할 때 오류)  -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger">
        {{ message }}
    </div>
    {% endfor %}
    <!-- 질문 내용 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">
                {{ question.content }}
            </div>
            <!--  첨부 이미지  -->
            {% if question.image_path %}
            <div class="my-3">
                <img src="{{ url_for('static', filename=question.image_path) }}" alt="첨부 이미지" style="max-width:100%; height: auto" class="img-thumbnail">
            </div>
            {% endif %}
             <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                 <div class="badge bg-light text-dark p-2 text-start">
                    <p class="mb-2">modified at</p>
                    <p class="mb-2">{{ question.modify_date|datetime }}</p>
                </div>
                 {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <p class="mb-2">{{ question.user.username }}</p>
                    <p class="mb-2">{{ question.create_date|datetime }}</p>
                </div>
            </div>
            <div class="my-3">
                {% if g.user == question.user %}
                <a href="{{ url_for('question.modify', question_id=question.id) }}" class="btn btn-sm btn-outline-secondary">수정</a>
                <button class="btn btn-sm btn-outline-danger delete" data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</button>
                <!-- question객체에 id컬럼을 가져오는 것 _는 다 변수 .은객체에 접근 / data- 라고 하면 사용자가 임의로 지정한 값(블로그에 정리되어있음) -->
                {% endif %}
            </div>
        </div>
    </div>


    <!-- 답변 내용 -->
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set|length }}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set %} <!--  for문 if문 같은 식들은 중괄호% 사이에 씀 -->
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">
                {{ answer.content }}
            </div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <p class="mb-2">modified at</p>
                    <p class="mb-2">{{ answer.modify_date|datetime }}</p>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <p class="mb-2">{{ answer.user.username }}</p>
                    <p class="mb-2">{{ answer.create_date|datetime }}</p>
                </div>
            </div>
            <div class="my-3">
                {% if g.user == answer.user %}
                <a href="{{ url_for('answer.modify', answer_id=answer.id) }}" class="btn btn-sm btn-outline-secondary">수정</a>
                <button class="btn btn-sm btn-outline-danger delete" data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</button>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 답변 등록 -->
    <form action="{{ url_for('answer.create', question_id= question.id)}}" method="post">
        {% include 'form_errors.html' %}
        <textarea {% if not g.user %} disabled {% endif %}
                  class="form-control" name="content" id="content" rows="5"></textarea>
        <button {% if not g.user %} disabled {% endif %}
                type="submit" class="btn btn-light mt-3">답변등록</button>
    </form>
</div>

{% endblock %}

{% block script %}
<script>
    const delete_elements = document.querySelectorAll('.delete');
    delete_elements.forEach(function(element){
        element.addEventListener('click', function(){
            if(confirm('정말로 삭제하시겠습니까?')){
                location.href = this.dataset.uri;
            }
        });
    });
</script>
{% endblock %}

<!-- script에서 74줄 location 객체에서 href로 이동시켜주는 것 -->

pybo/templates/question/question_form.html
{% extends 'base.html' %} <!-- base.html을 상속받는다는 뜻 -->
{% block content %}
<!-- 질문등록 -->
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="my-3" enctype="multipart/form-data">
        <!-- method 안 쓰면 기본 get 방식 / *form 형식에서 action 작성 안 하면 현재 경로에 요청* / enctype => 파일 업로드, 안 써주면 저장 X-->
       {% include 'form_errors.html' %}

        <div class="mb-3">
            <label for="subject">제목</label>
            <input type="text" name="subject" id="subject" class="form-control" value="{{ form.subject.data or '' }}">
            <!-- 오류가 나도 지워지지 않도록 해주고 빈 문자열을 NaN으로 나오는 걸 방지해주는 게 value -->
        </div>
        <div class="mb-3">
            <label for="content">내용</label>
            <textarea name="content" id="content" rows="5" class="form-control">{{ form.content.data or '' }}</textarea>
        </div>
        <div class="mb-3">
            <label for="image">이미지 첨부</label>
            <input type="file" name="image" id="image" class="form-control">
        </div>
<!--        {{ form.subject.label }}  question.views에 있는 form한테 전송받는 것  -->
<!--        {{ form.subject(class="form-control") }}  => 여기 두 줄이 위에 제목 div class="mb-3"  -->
<!--        {{ form.content.label }}-->
<!--        {{ form.content(class="form-control") }}  => 여기 두 줄이 아래 내용 div class="mb-3"  -->
        <button type="submit" class="btn btn-light">저장하기</button>
    </form>
</div>
{% endblock %}

pybo/templates/question/question_list.html
<!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"> base에 있어서 안 써도 됨-->
{% extends 'base.html' %} <!-- base.html을 상속받는다는 뜻 -->
{% block content %}
<div class="container my-3">
    <!--  검색 기능 추가  -->
    <div class="row my-3">
        <div class="col-6">
            <!--  질문 등록 버튼  -->
            <a href="{{ url_for('question.create') }}" class="btn btn-outline-secondary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-hover">
        <thead>
        <tr class="table-dark">
            <th scope="col">번호</th>
            <th scope="col">제목</th>
            <th scope="col">글쓴이</th>
            <th scope="col">작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list.items %}
        <tr>
            <td>{{ question_list.total - (question_list.page - 1) * question_list.per_page - loop.index0 }}</td>
            <td>
                {% if question.image_path %}
                <img src="{{ url_for('static', filename=question.image_path) }}" alt="썸네일" style="width:50px;">
                {% endif %}
                <a href="{{ url_for('question.detail', question_id = question.id) }}">{{ question.subject }}</a>
                {% if question.answer_set | length > 0 %}
                <span class="text-danger small"> [{{ question.answer_set | length }}] </span>
                {% endif %}
            </td>
            <td>{{ question.user.username }}</td>
            <td>{{ question.create_date|datetime }}</td>
        </tr>
        {% endfor %} {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <!--  페이징 처리  -->
    <ul class="pagination justify-content-center">
        <!--  이전 버튼  -->
        {% if question_list.has_prev %}
        <li class="page-item"><a data-page="{{ question_list.prev_num }}" href="javascript:void(0)" class="page-link">Prev</a></li>
        {% else %}
        <li class="page-item disabled"><a href="javascript:void(0)" class="page-link">Prev</a></li>
        <!--  void(0) => 리턴값이 X => 동작 안 함  -->
        {% endif %}

        <!--  페이지 번호  -->
        {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != question_list.page %}
        <!--  일반적인 page  -->
        <li class="page-item">
            <a data-page="{{ page_num }}" class="page-link" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% else %}
        <!--  현재 page  -->
        <li class="page-item active">
            <a class="page-link" href="javascript:void(0)" aria-current="page">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript: void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}

        <!--  다음 버튼  -->
        {% if question_list.has_next %}
        <li class="page-item">
        <!--  우리가 직접 변경
        <a href="?page={{ question_list.next_num }}" class="page-link">Next</a>  -->
        <!--  자바로 변경 -->
            <a data-page="{{ question_list.next_num }}" href="javascript:void(0)" class="page-link">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a href="javascript:void(0)" class="page-link">Next</a></li>
        <!--  void(0) => 리턴값이 X => 동작 안 함  -->
        {% endif %}
    </ul>
    <!-- get방식으로 보내니까 url에 딸려가서 보내줌 -->
    <form action="{{ url_for('question._list') }}" method="GET" id="searchForm">
        <input type="hidden" name="kw" id="kw" value="{{ kw or '' }}">
        <input type="hidden" name="page" id="page" value="{{ page }}">
    </form>
</div>
{% endblock %}

<!-- 질문 목록 -->
<!-- {% if question_list %} -->
<!--    <ul> -->
<!--        {% for question in question_list %} -->
<!--       <li><a href="{{ url_for('question.detail', question_id = question.id) }}">{{question.subject}}</a></li> -->
<!--        {% endfor %} -->
<!--    </ul> -->
<!-- {% else %} -->
<!--    <p>질문이 없습니다.</p> -->
<!-- {% endif %} -->

{% block script %}
<script>
    // 페이지 버튼 클릭시 동작
    const page_elements = document.querySelectorAll('.page-link');
    page_elements.forEach(function(element){
        element.addEventListener('click', function(){
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        })
    })

    // 검색 버튼 클릭시 동작
    const btn_search = document.getElementById('btn_search');
    btn_search.addEventListener('click', function(){
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;
        document.getElementById('searchForm').submit();
    })
</script>
{% endblock %}